name: Build Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Signing info
  SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
  SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Generate APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
